import mongoose from "mongoose";

const { Schema } = mongoose;

const demostockSchema = new Schema({
  // // Symbol: String,
  // Symbol: { type: String, required: true },
  // Price: String,
  // DataAsOf: String,
  // AssetType: String,
  // Name: String,
  // Description: String,
  // CIK: String,
  // Exchange: String,
  // Currency: String,
  // Country: String,
  // Sector: String,
  // Industry: String,
  // Address: String,
  // FiscalYearEnd: String,
  // LatestQuarter: String,
  // MarketCapitalization: String,
  // EBITDA: String,
  // PERatio: String,
  // PEGRatio: String,
  // BookValue: String,
  // DividendPerShare: String,
  // DividendYield: String,
  // EPS: String,
  // RevenuePerShareTTM: String,
  // ProfitMargin: String,
  // OperatingMarginTTM: String,
  // ReturnOnAssetsTTM: String,
  // ReturnOnEquityTTM: String,
  // RevenueTTM: String,
  // GrossProfitTTM: String,
  // DilutedEPSTTM: String,
  // QuarterlyEarningsGrowthYOY: String,
  // QuarterlyRevenueGrowthYOY: String,
  // AnalystTargetPrice: String,
  // TrailingPE: String,
  // ForwardPE: String,
  // PriceToSalesRatioTTM: String,
  // PriceToBookRatio: String,
  // EVToRevenue: String,
  // EVToEBITDA: String,
  // Beta: String,
  // // 52WeekHigh: String,
  // // 52WeekLow: String,
  // // 50DayMovingAverage: String,
  // // 200DayMovingAverage: String,
  // _52WeekHigh: String,
  // _52WeekLow: String,
  // _50DayMovingAverage: String,
  // _200DayMovingAverage: String,
  // SharesOutstanding: String,
  // DividendDate: String,
  // ExDividendDate: String,
  //! new
  Symbol: { type: String, required: true },
  Price: Number,
  DataAsOf: String,
  AssetType: String,
  Name: String,
  Description: String,
  CIK: String,
  Exchange: String,
  Currency: String,
  Country: String,
  Sector: String,
  Industry: String,
  Address: String,
  FiscalYearEnd: String,
  LatestQuarter: String,
  MarketCapitalization: Number,
  EBITDA: Number,
  PERatio: Number,
  PEGRatio: Number,
  BookValue: Number,
  DividendPerShare: Number,
  DividendYield: Number,
  EPS: Number,
  EPSx15: Number,
  RevenuePerShareTTM: Number,
  ProfitMargin: Number,
  OperatingMarginTTM: Number,
  ReturnOnAssetsTTM: Number,
  ReturnOnEquityTTM: Number,
  RevenueTTM: Number,
  GrossProfitTTM: Number,
  DilutedEPSTTM: Number,
  QuarterlyEarningsGrowthYOY: Number,
  QuarterlyRevenueGrowthYOY: Number,
  AnalystTargetPrice: Number,
  TrailingPE: Number,
  ForwardPE: Number,
  PriceToSalesRatioTTM: Number,
  PriceToBookRatio: Number,
  EVToRevenue: Number,
  EVToEBITDA: Number,
  Beta: Number,
  // 52WeekHigh: Number,
  // 52WeekLow: Number,
  // 50DayMovingAverage: Number,
  // 200DayMovingAverage: Number,
  _52WeekHigh: Number,
  _52WeekLow: Number,
  _50DayMovingAverage: Number,
  _200DayMovingAverage: Number,
  SharesOutstanding: Number,
  DividendDate: String,
  ExDividendDate: String,
  Bruchwert52Week: Number,
  Favorites: [String], // Field "Favorites" is Array of Strings
  // zzzTest: String,
  LogoURL: String,
});

// check whether the model with this name has already been compiled and if yes, take the already compiled model
const Demostock =
  mongoose.models.Demostock || mongoose.model("Demostock", demostockSchema);

export default Demostock;
